server {
    listen 80;
    server_name _;
    return 301 https://;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /mnt/MolStar/nginx/certs/molstar.crt;
    ssl_certificate_key /mnt/MolStar/nginx/certs/molstar.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    root /mnt/MolStar/server/molstar-app/dist;
    index index.html;
    client_max_body_size 500M;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_connect_timeout 10s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
